### ISSUE TITLE
Check on test_release branch

### ISSUE THREAD

**Issue by lizliz** [MunchLab/ceREEBerus#51]
There appears to be a test_release branch, but I'm not sure that my pull request ever involved it. Want to set this up in the style of teaspoon, so 

- No one can push directly to master
- Pull requests require at least one thumbs up (not sure if this should require me, maybe it should at least for now)
- Pull request goes into test_release first (?is this what teaspon does?) 
- Then it goes into the master when we're ready

I think I'm going to need help from @barnesd8 on this one since I don't fully understand how this party works.

**Comment by barnesd8** [comment]
Done!
